### ISSUE TITLE
G1 high level api only works for damping and standing mode

### ISSUE THREAD

**Issue by YandongJi** [unitreerobotics/unitree_sdk2_python#22]
Hi I tried running `python3 ./example/g1/high_level/g1_loco_client_example.py eth0` but it only works for standing and damping mode, could you check whether this works on your end? Thanks

**Comment by YandongJi** [comment]
add self.Start() before this line https://github.com/unitreerobotics/unitree_sdk2_python/blob/c52f48b0b55f29dbc6ed3f67303bbd25732dc069/unitree_sdk2py/g1/loco/g1_loco_client.py#L96

**Comment by Rusteam** [comment]
> add self.Start() before this line
> 
> https://github.com/unitreerobotics/unitree_sdk2_python/blob/c52f48b0b55f29dbc6ed3f67303bbd25732dc069/unitree_sdk2py/g1/loco/g1_loco_client.py#L96

did you get the `Squat()` and `StandUp()` commands running fine?
For me the robot goes into unbalanced and falls when these methods are called.
