### ISSUE TITLE
[ClientStub] send request error.

### ISSUE THREAD

**Issue by Lin-jun-xiang** [unitreerobotics/unitree_sdk2_python#6]
## Problem

* Using the unitree app API mode to connect the go2  to the same Wi-Fi as the computer. The network card name is set as `Wi-Fi` which get by `ipconfig>> InterfaceAlias: Wi-Fi`.

* When running `example/helloworld/`, the `publisher` and `subscriber` work smoothly and produce the expected results.

* However, when executing `test.StandDown()`, an error occurs with the message `"[ClientStub] send request error. id=xxx"`.

The client error cause from:
https://github.com/unitreerobotics/unitree_sdk2_python/blob/bd24b5be05b67eb044ebcec9f35d0698040b5360/unitree_sdk2py/rpc/client_stub.py#L50-L55

I have used debug mode, then find the `self.___publication_matched_count` is `0` which cause the client error.

https://github.com/unitreerobotics/unitree_sdk2_python/blob/bd24b5be05b67eb044ebcec9f35d0698040b5360/unitree_sdk2py/core/channel.py#L129-L140

However, I have no idea why the `self.___publication_matched_count` is `0`.

---
## Environment
- **Go2**: go2 air and go2 pro have been tested
- **Operating System**: Both Windows 10 and WSL2 (Ubuntu20.04) have been tested
- **Python Version**: 3.8.6

**Comment by shy114514** [comment]
Hi, I met the same problem. Could you please tell me how you solved the problem?

**Comment by BeNavon** [comment]
> ## Problem
> * Using the unitree app API mode to connect the go2  to the same Wi-Fi as the computer. The network card name is set as `Wi-Fi` which get by `ipconfig>> InterfaceAlias: Wi-Fi`.
> * When running `example/helloworld/`, the `publisher` and `subscriber` work smoothly and produce the expected results.
> * However, when executing `test.StandDown()`, an error occurs with the message `"[ClientStub] send request error. id=xxx"`.
> 
> I have used debug mode, then find the `self.___publication_matched_count` is `0` which cause the client error.
> 
> https://github.com/unitreerobotics/unitree_sdk2_python/blob/bd24b5be05b67eb044ebcec9f35d0698040b5360/unitree_sdk2py/core/channel.py#L129-L140

Hi @Lin-jun-xiang , 
I'm trying to run the high-level control example `go2_sport_client.py` using the `unitree_mujoco` simulation and specifying the network interface `lo`. I encountered the same error message you've mentioned:
`[ClientStub] send request error. id: 252906806156372`
Did you figure out how to solve it?

**Comment by Rusteam** [comment]
I was getting these errors on `python 3.12` and then I switched to `3.10` and that fixed it (with restarting a robot).

**Comment by xkhainguyen** [comment]
@Rusteam 
have you got any of these scripts working in Mujoco simulation?

**Comment by kumar-abhina** [comment]
@Rusteam I am using Python 3.10 but issue is still there I am unable to send high level commands to the robot

**Comment by Rusteam** [comment]
Is cyclonedds installed correctly and
you can ping the robot?

**Comment by lambdavi** [comment]
I am getting the same error. I can ping the robot but I get: [ClientStub] send request error

**Comment by Rusteam** [comment]
One of the libs is not installed correctly. Can you post you python and cyclonedds versions?

**Comment by lambdavi** [comment]
I am working with Python 3.10.17 and cyclonedds==0.10.2 
I can ping the robot and also setup the ssh connection. 
Using the c++ sdk and running the stand script, I get all zero values during printing and no response from the go2. With the python version I get the error above.
Both of them seem to be installed correctly without any warning/error.

**Comment by Rusteam** [comment]
My versions are almost identical. I haven't tested with go2. Maybe go2 firmware update is needed?

**Comment by lambdavi** [comment]
Hardware version: 2.0
Software version: 1.1.4 (from app)
It's really strange. I can get it more or less work using this repo: https://github.com/Teddy-Liao/walk-these-ways-go2
but it's crazy I can't get it to work with this one. Are there particular network settings I have to use (local mode vs wifi mode)?

**Comment by Rusteam** [comment]
How do you pass the network interface argument?

**Comment by lambdavi** [comment]
I tried again with Python 3.9 and it worked. But only for stand up/down. The others skills unfortunately are not working.

**Comment by wangtao716** [comment]
@lambdavi move and other commands don't work because the robot dog will lock the joint after stand up, you should first unlock the joint

**Comment by YuehChuan** [comment]
For people who is struggling this  bug.
Try enable motion_switcher to "ai" mode.

unitree_sdk2_python installed.

1.  SSH into pc2 
ssh unitree@192.168.123.164

2. python3 motion_switcher_example.py eth0

3. Restart G1 robot.

https://github.com/unitreerobotics/unitree_sdk2_python/blob/master/example/motionSwitcher/motion_switcher_example.py

<img width="1062" height="156" alt="Image" src="https://github.com/user-attachments/assets/ae835023-3304-4497-9edc-c4ddc53778a3" />
